version: '3.8'
services:
  eli-open-api:
    container_name: eli-open-api
    # image: docker-image:tag
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3002:3002'
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - open-api-network

  db-eli-open-api:
    image: postgres:16-alpine
    container_name: db-eli-open-api
    restart: on-failure
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: eli_partners
    networks:
      - open-api-network

networks:
  open-api-network:
    name: open-api-network
    external: false
