version: '3.8'
services:
  eli-open-api:
    container_name: eli-open-api
    # image: docker-image:tag
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '10077:10077'
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - open-api-network

networks:
  open-api-network:
    name: open-api-network
    external: false
