version: '3.8'
services:
  eli-open-api:
    container_name: eli-open-api
    # image: docker-image:tag
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3005:3005'
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - open-api-network

  eli-open-api-redis:
    image: redis:7.2.2-alpine
    container_name: eli-open-api-redis
    restart: on-failure
    ports:
      - 6377:6379
    networks:
      - open-api-network

  db-eli-open-api:
    image: postgres:16-alpine
    container_name: db-eli-open-api
    restart: on-failure
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db_payment
    networks:
      - open-api-network

networks:
  open-api-network:
    name: open-api-network
    external: false
